MONGODB_HOST: mongodb-{{ env }}.jayani23.fun # mongodb-dev.jayani23.fun
REDIS_HOST: redis-{{ env }}.jayani23.fun
CATALOGUE_HOST: catalogue-{{ env }}.jayani23.fun
CART_HOST: cart-{{ env }}.jayani23.fun
USER_HOST: user-{{ env }}.jayani23.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.jayani23.fun
MYSQL_HOST: mysql-{{ env }}.jayani23.fun
SHIPPING_HOST: shipping-{{ env }}.jayani23.fun
PAYMENT_HOST: payment-{{ env }}.jayani23.fun